### ISSUE TITLE
 What does the cpFuncs field in the AbstractExtractionGenerator class mean？

### ISSUE THREAD

**Issue by Feyily** [david-kamensky/tIGAr#10]
Hello, David. I want to modify the `tIGAr` framework to support bezier tetrahedron, but I don't understand what the `cpFuncs` field does in `AbstractExtractionGenerator` and what it means. I'm sorry to submit code-independent problem in issue.

**Comment by david-kamensky** [comment]
The attribute `cpFuncs` is a list of `Function`s giving finite element representations of the homogeneous components of the mapping from spline parameter space (where the `mesh` is defined) to physical space.  (The variable name is an abbreviation of "control point functions".)  Perhaps looking at how `cpFuncs` is used to define the `F` mapping of an `ExtractedSpline` (currently in lines 918--921 of `common.py`) may clarify its geometric interpretation.

**Comment by Feyily** [comment]
OK, I understand now. Thanks for your reply.
