### ISSUE TITLE
using eval with tigar

### ISSUE THREAD

**Issue by gcdiwan** [david-kamensky/tIGAr#12]
Hi David,

Would you expect the eval to work the same as in fenics? The following segment ends up in error:
xx = np.linspace(0, 1, num=100)
uu = np.zeros_like(xx)
for i in np.arange(0, xx.size):
    uu[i] = u([xx[i],xx[i]])

error below:

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~/wgiga.py in <module>
    117 uu = np.zeros_like(xx)
    118 for i in np.arange(0, xx.size):
--> 119     uu[i] = uwg([xx[i],xx[i]])
    120 
    121 # C = Constant((1e-3, 0.0))

/usr/lib/petsc/lib/python3/dist-packages/dolfin/function/function.py in __call__(self, *args, **kwargs)
    353 
    354         # The actual evaluation
--> 355         self._cpp_object.eval(values, x)
    356 
    357         # If scalar return statement, return scalar value.

RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to intersect cell and point.
*** Reason:  Intersection is only implemented for simplex meshes.
*** Where:   This error was encountered inside Cell.cpp.
*** Process: 0
*** 
*** DOLFIN version: 2019.2.0.dev0
*** Git changeset:  unknown
*** -------------------------------------------------------------------------

Any suggestions/comments on what i might be doing wrong here? Many thanks.
Ganesh

**Comment by david-kamensky** [comment]
Hi Ganesh,

DOLFIN `Function` objects used in tIGAr can be evaluated at points, but with some caveats:
* The domains of these `Function`s are the spline parameter space, not physical space, so you need to pass the parametric coordinates of the point at which you want to evaluate a `Function`.
* Old DOLFIN cannot evaluate `Function`s at points on quad/hex meshes, so you would need to extract the spline basis to higher-order simplex (tri/tet) elements.  This is mathematically possible and supported in tIGAr, but assembly of variational forms becomes less efficient, especially in 3D.  (To do this, you would pass the optional keyword argument `useRect=False` to the control mesh constructor.)  Quad/hex support is better in DOLFINx, but tIGAr has not been ported to DOLFINx.
* When using rational splines (e.g., NURBS with a weight function that is not everywhere equal to one), the `Function` object is the solution in homogeneous coordinates, and needs to be divided through by the weight to get the true rational solution.  You cannot do point evaluation of a UFL `Division` object, so you would need to evaluate both the homogeneous solution and the weight, then take the quotient of these point evaluations.  

Best, David
