### ISSUE TITLE
point evaluation

### ISSUE THREAD

**Issue by beksar** [david-kamensky/tIGAr#14]
how do I evaluate displacement on a particular point when using IGA? 

When "u" is the solution for any problem, I try first:

print(u.at(point1, point2)), it gives error like:
AttributeError: 'Function' object has no attribute 'at'. 

secondly tried: 
u_new = project(u, Function(VectorFunctionSpace(splineMesh, "P", p)))
u_new.at(point1,point2), giving error:

AttributeError: 'ExplicitBSplineControlMesh' object has no attribute 'ufl_cell'.

**Comment by david-kamensky** [comment]
At least in legacy FEniCS (which is what tIGAr is based on), the Python `__call__()` method of the `Function` class is overloaded for function evaluation, so, for a `Function` object `u`, you can use syntax like `u_at_point = u(point)`, where `point` is a `Point` object that can be initialized directly from coordinates, e.g., `point = Point(x,y)` for `float`s `x` and `y`.  

One thing to watch out for is that, when using rational splines (e.g., NURBS with non-unit weights), the FEniCS `Function` in the solution is in homogeneous form, and needs to be divided through by weight to get the "true" solution.  (See the demos for examples of this, where I used the notation `u_hom` for the homogeous solution corresponding to `u`.)  This rational spline solution would be a `Division` object, which cannot be directly evaluated at points.  Thus, you'd need to separately evaluate the homogeneous solution and weight `Function`s, then divide the resulting `float`s.
