### ISSUE TITLE
Unable to install tIGAr in ubuntu for doflinx

### ISSUE THREAD

**Issue by bagla0** [david-kamensky/tIGAr#16]
Since tIGAR was built on doflin, I tried using it in fenicsx (dolfinx), but, unable to install the libraries. Can you provide the steps for installation ?

The another query related to implementing in dolfinx:
Can this be used to define the functionspace similar to other dolfinx
 ``` 
dolfinx.fem.functionspace(mesh, basix.ufl.element(
    "S", mesh.topology.cell_name(), deg, shape=(3, )))
 ``` 
by replacing S with any other C1 continuity function?

**Comment by david-kamensky** [comment]
tIGAr is only compatible with Legacy FEniCS, not FEniCSx.  However, it's possible to have both Legacy FEniCS and FEniCSx installed simultaneously on the same system without interfering with each other.  You can follow the instructions [here](https://fenicsproject.org/download/archive/) to install Legacy FEniCS on Ubuntu.

The construction of function spaces and formulation of problems using tIGAr is somewhat different from standard FEniCS (or FEniCSx); the best guide would be the examples included in the `demos` subdirectory of the repository.
