### ISSUE TITLE
Can you install igakit? I don't know why I can't install it

### ISSUE THREAD

**Issue by zhangyancq** [david-kamensky/tIGAr#17]

**Comment by david-kamensky** [comment]
I tried just now on an Ubuntu Linux machine, and the installation itself runs okay for me following the instructions [here](https://github.com/dalcinl/igakit) (although I substituted `pip3` for `pip` and `python3` for `python` in the two sets of instructions).  However, I get an error `undefined symbol: Npy__PyLong_AsInt` when running `from igakit.nurbs import NURBS`.  I don't know how to resolve this off the top of my head, and it's independent of tIGAr, so I would try posting an issue directly on the igakit repository instead if this is the error you're getting.

**Comment by zhangyancq** [comment]
Thank you very much for your reply. I have already raised questions in the igakit section. I was able to install tIGAr, but I couldn't install igakit. I think it's probably because of the Windows system I use. Then I am also a novice, so there are some problems that can not be solved at present. Have a nice day
