### ISSUE TITLE
AttributeError: 'petsc4py.PETSc.Mat' object has no attribute 'PtAP'

### ISSUE THREAD

**Issue by GabrielJie** [david-kamensky/tIGAr#4]
Dear David,

When I run a demo (poisson.py), a problem occur "AttributeError: 'petsc4py.PETSc.Mat' object has no attribute 'PtAP'" in a function (common.py).

I also have seen your common install issue that is due to an old version of petsc4py. However, in my computer, I have installed the petsc4py package into Pycharm using Ubuntu 18.04. The version of petsc4py is 3.12.0. It is new.
Meanwhile, I have searched for a different version of petsc4py, namely "python3-petsc4py_3.7.0-3build2_amd64.deb (https://ubuntu.pkgs.org/18.04/ubuntu-universe-amd64/python3-petsc4py_3.7.0-3build2_amd64.deb.html)". After installation, I import it into python3 (python3 -c "import python3-petsc4py"), and it is still wrong. it shows that the valid syntax. What is the difference between petsc4py and python3-petsc4py ?

I am very confused about this problem, and how to resolve it ?

With best regards,
Jie.

**Comment by david-kamensky** [comment]
I usually use `pip3` to install `petsc4py` on Ubuntu.  I've never tried using PyCharm.  While I'd recommend trying to resolve this installation issue, a less-than-ideal workaround would to edit the value of the variable `FORM_MT` in `tIGAr/common.py`.  (Setting this to `True` should cause the matrix `$M^T$` to be explicitly formed, then used in the product `$M^T A M$` with regular matrix--matrix multiplication, although it's something I put in for debugging when first switching to `PtAP`, so I haven't tested with `FORM_MT=True` in some time.)

**Comment by GabrielJie** [comment]
Thanks for your reply.

Let me have a try again. Could you tell me what is your development environment, like using docker ?

With best regards,
Jie.

**Comment by david-kamensky** [comment]
Mostly I use Ubuntu, with FEniCS installed via the package manager, edit code in a basic text editor, and run scripts from the command line.  The Singularity recipe `singularity-recipe.def` included in the repository should give reproducible behavior.  (If you already have Docker figured out, you could just execute the setup steps in the `%post` section within a Docker container instead of building a Singularity image from the recipe file.)

**Comment by GabrielJie** [comment]
ok, Thanks for your reply.

With best regards,
Jie.
