### ISSUE TITLE
ExtractedNonlinearSolver

### ISSUE THREAD

**Issue by wb-zhang** [david-kamensky/tIGAr#5]
Hi David, I just noticed that you might accidentally comment [`self.solver.solve(self.problem,tempVec)`](https://github.com/david-kamensky/tIGAr/blob/master/tIGAr/common.py#L581) in `ExtractedNonlinearSolver.solve`.

**Comment by david-kamensky** [comment]
Yes, thanks for pointing that out!  While it's easy to fix on my end, I'd encourage you to submit a pull request resolving this issue, so you are clearly credited for your contribution.
